import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultDashboard,validateDashboard,placeWidget,addWidget,overlaps,GRID} from '../dist/dashboard-model.js';
import {initialScene,validateScene,SceneStore} from '../dist/model.js';
import {MockHub} from '../dist/adapters.js';
test('default square dashboard fits without overlaps',()=>assert.deepEqual(validateDashboard(defaultDashboard()),defaultDashboard()));
test('legacy configurations gain dashboard defaults without mutating input',()=>{const legacy=initialScene();delete legacy.dashboard;const result=validateScene(legacy);assert.deepEqual(result.dashboard,defaultDashboard());assert.equal(legacy.dashboard,undefined);});
test('resize can shrink and expand while preserving valid grid',()=>{let d=defaultDashboard();d=placeWidget(d,'energy',{w:3});assert.equal(d.widgets.find(w=>w.id==='energy').w,3);d=placeWidget(d,'energy',{w:6});assert.deepEqual(d,defaultDashboard());});
test('moving a tile reflows displaced tiles',()=>{const d=placeWidget(defaultDashboard(),'home',{x:2,y:0});assert.equal(d.widgets.find(w=>w.id==='home').x,2);assert.equal(d.widgets.find(w=>w.id==='weather').x,0);assert.deepEqual(validateDashboard(d),d);});
test('resizing collision cannot corrupt original state',()=>{const d=defaultDashboard(),before=structuredClone(d);assert.throws(()=>placeWidget(d,'camera',{x:0,y:0,w:6,h:24}),/space/);assert.deepEqual(d,before);});
for(const patch of [{x:-1},{y:24},{w:7},{h:25},{w:1},{h:1},{x:.5},{h:NaN}])test('invalid grid transform rejected '+JSON.stringify(patch),()=>assert.throws(()=>placeWidget(defaultDashboard(),'home',patch)));
test('removed space admits a new widget',()=>{const d=defaultDashboard();d.widgets=d.widgets.filter(w=>w.type!=='weather');const next=addWidget(d,'air','co2');assert.equal(next.widgets.find(w=>w.id==='co2').x,2);assert.equal(next.widgets.length,6);});
test('widgets flow below the visible dashboard',()=>{const d=addWidget(defaultDashboard(),'air','a');assert.equal(d.widgets.at(-1).y,7);});
test('full grid reports no capacity',()=>assert.throws(()=>addWidget({clockMaterial:'glass',widgets:[{id:'all',type:'home',x:0,y:0,w:6,h:24}]},'air','a'),/space/));
test('duplicates, unknown types, overlaps and invalid finishes rejected',()=>{for(const mutate of [d=>d.widgets.push({...d.widgets[0]}),d=>d.widgets[0].type='eval',d=>d.widgets[1].x=0,d=>d.clockMaterial='script']){const d=defaultDashboard();mutate(d);assert.throws(()=>validateDashboard(d));}});
test('touching edges are not overlaps',()=>assert.equal(overlaps({x:0,y:0,w:2,h:2},{x:2,y:0,w:2,h:2}),false));
test('layout and clock finish participate in undo/redo',()=>{const s=new SceneStore(initialScene());s.edit(x=>{x.dashboard=placeWidget(x.dashboard,'energy',{w:3});x.dashboard.clockMaterial='chrome';});s.undo();assert.equal(s.scene.dashboard.clockMaterial,'glass');s.redo();assert.equal(s.scene.dashboard.clockMaterial,'chrome');assert.equal(s.scene.dashboard.widgets.at(-1).w,3);});
test('hub roundtrip preserves widget layout and material per profile',async()=>{const h=new MockHub({latency:0});const scene=initialScene('space');scene.dashboard.clockMaterial='amber';scene.dashboard=placeWidget(scene.dashboard,'energy',{w:3});await h.save('tv',scene,0);assert.deepEqual((await h.pull('tv')).scene,scene);assert.equal((await h.pull('desktop')).scene.dashboard.clockMaterial,'glass');});
test('deterministic stress sequence keeps every accepted layout within bounds',()=>{let d=defaultDashboard();for(let i=0;i<500;i++){const target=d.widgets[i%d.widgets.length];try{d=placeWidget(d,target.id,{x:(i*7)%GRID.columns,y:(i*3)%GRID.rows});}catch{}assert.deepEqual(validateDashboard(d),d);}});
